---
name: Run Tox

# yamllint disable rule:truthy
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Tox tests
        id: test
        uses: fedora-python/tox-github-action@main
        with:
          tox_env: py312,lint

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
